import asyncio
import re
import nbformat
from nbconvert import HTMLExporter
from playwright.async_api import async_playwright

async def export_notebook_to_pdf(notebook_path: str, output_pdf_path: str) -> None:
    # 1. Convert Notebook to HTML
    html_exporter = HTMLExporter()
    notebook = nbformat.read(notebook_path, as_version=4)
    html_data, _ = html_exporter.from_notebook_node(notebook)

    # 2. THE FIX: Aggressively rip out all Base64 embedded fonts generated by Jupyter.
    # nbconvert hardcodes custom fonts as Base64 data inside @font-face blocks. 
    # This regex completely deletes them so Chromium is forced to use clean system TrueType fonts.
    html_data = re.sub(r'@font-face\s*\{.*?\}', '', html_data, flags=re.DOTALL)

    # 3. Inject CSS to guarantee system TrueType fonts take over the empty spaces
    pdf_clean_head = """
    <style>
        * {
            font-family: 'Segoe UI', Arial, sans-serif !important;
        }
        code, pre, .highlight, .jp-CodeCell, .CodeMirror {
            font-family: 'Consolas', 'Courier New', monospace !important;
        }
    </style>
    """
    html_data = html_data.replace("</head>", f"{pdf_clean_head}</head>")

    # 4. Render PDF with Playwright
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        
        # Load content and wait for network
        await page.set_content(html_data, wait_until="networkidle")
        
        await page.pdf(
            path=output_pdf_path,
            format="A4",
            print_background=True,
            margin={"top": "0.8in", "right": "0.8in", "bottom": "0.8in", "left": "0.8in"}
        )
        await browser.close()

if __name__ == "__main__":
    notebook_file = "01_Raul_Contreras_Algoritmos_AG3_revisado.ipynb"
    pdf_file = "01_Raul_Contreras_Algoritmos_AG3_revisado.pdf"
    
    asyncio.run(export_notebook_to_pdf(notebook_file, pdf_file))
    print(f"Successfully generated clean PDF: {pdf_file}")